[package]
name = "coffee-tracking"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.42", features = [ "alloc" ] }
crossterm = "0.29.0"
ratatui = "0.29.0"
uuid = { version = "1.18.1", features = [ "v4" ] }
